<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="株式会社光和は、長野県飯田市で「ご葬儀からご創儀へ」をコンセプトに、心を込めた葬儀サービスを提供しています。24時間365日対応、各種葬儀プランをご用意しております。">
    <meta name="keywords" content="葬儀,葬儀場,メモリアルホール,光和,飯田市,長野県,家族葬,一般葬,直葬,24時間対応,創儀">
    <meta name="author" content="株式会社光和">
    <meta name="robots" content="index, follow">
    <meta name="googlebot" content="index, follow">
    <link rel="canonical" href="<?php echo esc_url(home_url(add_query_arg(array(), $wp->request) ? '/' . add_query_arg(array(), $wp->request) . '/' : '/')); ?>">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<?php echo esc_url(home_url(add_query_arg(array(), $wp->request) ? '/' . add_query_arg(array(), $wp->request) . '/' : '/')); ?>">
    <meta property="og:title" content="<?php wp_title('|', true, 'right'); ?>株式会社光和">
    <meta property="og:description" content="株式会社光和は、長野県飯田市で「ご葬儀からご創儀へ」をコンセプトに、心を込めた葬儀サービスを提供しています。24時間365日対応、各種葬儀プランをご用意しております。">
    <meta property="og:image" content="<?php echo esc_url(get_theme_file_uri('images/logo.png')); ?>">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:site_name" content="株式会社光和">

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="<?php wp_title('|', true, 'right'); ?>株式会社光和">
    <meta name="twitter:description" content="株式会社光和は、長野県飯田市で「ご葬儀からご創儀へ」をコンセプトに、心を込めた葬儀サービスを提供しています。24時間365日対応、各種葬儀プランをご用意しております。">
    <meta name="twitter:image" content="<?php echo esc_url(get_theme_file_uri('images/logo.png')); ?>">

    <!-- Title tag is automatically generated by WordPress via add_theme_support('title-tag') -->
    <!-- CSS/JS are loaded via functions.php using wp_enqueue_style() and wp_enqueue_script() -->

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="<?php echo esc_url(get_theme_file_uri('images/favicon.png')); ?>">
    <link rel="apple-touch-icon" href="<?php echo esc_url(get_theme_file_uri('images/favicon.png')); ?>">
    
    <!-- JSON-LD Structured Data -->
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Organization",
                "@id": "https://mh-kowa.com/#organization",
                "name": "株式会社光和",
                "alternateName": "株式会社光和",
                "url": "https://mh-kowa.com/",
                "logo": "<?php echo esc_url(get_theme_file_uri('images/logo.png')); ?>",
                "contactPoint": [
                    {
                        "@type": "ContactPoint",
                        "telephone": "+81-120-077-508",
                        "contactType": "customer service",
                        "availableLanguage": "Japanese",
                        "areaServed": "JP",
                        "contactOption": "TollFree"
                    },
                    {
                        "@type": "ContactPoint",
                        "telephone": "+81-265-53-2111",
                        "contactType": "customer service",
                        "availableLanguage": "Japanese",
                        "areaServed": "JP"
                    }
                ],
                "address": {
                    "@type": "PostalAddress",
                    "addressCountry": "JP",
                    "addressRegion": "長野県",
                    "addressLocality": "飯田市",
                    "streetAddress": "松尾新井6544-1",
                    "postalCode": "395-0821"
                }
            },
            {
                "@type": "FuneralHome",
                "@id": "https://mh-kowa.com/#localbusiness",
                "name": "株式会社光和",
                "description": "長野県飯田市の葬儀場。「ご葬儀からご創儀へ」をコンセプトに、心を込めた葬儀サービスを提供しています。24時間365日対応。",
                "url": "https://mh-kowa.com/",
                "telephone": "+81-120-077-508",
                "priceRange": "¥¥〜¥¥¥",
                "address": {
                    "@type": "PostalAddress",
                    "addressCountry": "JP",
                    "addressRegion": "長野県",
                    "addressLocality": "飯田市",
                    "streetAddress": "松尾新井6544-1",
                    "postalCode": "395-0821"
                },
                "geo": {
                    "@type": "GeoCoordinates",
                    "latitude": 35.4877,
                    "longitude": 136.9537
                },
                "openingHoursSpecification": {
                    "@type": "OpeningHoursSpecification",
                    "dayOfWeek": ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
                    "opens": "00:00",
                    "closes": "23:59"
                },
                "areaServed": {
                    "@type": "GeoCircle",
                    "geoMidpoint": {
                        "@type": "GeoCoordinates",
                        "latitude": 35.4877,
                        "longitude": 136.9537
                    },
                    "geoRadius": "30000"
                },
                "hasOfferCatalog": {
                    "@type": "OfferCatalog",
                    "name": "葬儀プラン",
                    "itemListElement": [
                        {
                            "@type": "Offer",
                            "itemOffered": {
                                "@type": "Service",
                                "name": "一般葬",
                                "description": "伝統的な葬儀形式で、多くの参列者をお迎えする葬儀プラン"
                            }
                        },
                        {
                            "@type": "Offer",
                            "itemOffered": {
                                "@type": "Service",
                                "name": "家族葬",
                                "description": "ご家族・親族中心の温かく静かなお別れの時間を大切にした葬儀プラン"
                            }
                        }
                    ]
                }
            },
            {
                "@type": "WebSite",
                "@id": "https://mh-kowa.com/#website",
                "url": "https://mh-kowa.com/",
                "name": "株式会社光和",
                "description": "長野県飯田市の葬儀場。「ご葬儀からご創儀へ」をコンセプトに、心を込めた葬儀サービスを提供しています。",
                "publisher": {
                    "@id": "https://mh-kowa.com/#organization"
                }
            },
            {
                "@type": "BreadcrumbList",
                "@id": "https://mh-kowa.com/#breadcrumb",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "ホーム",
                        "item": "https://mh-kowa.com/"
                    }
                ]
            }
        ]
    }
    </script>
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
    <?php wp_body_open(); ?>

    <!-- Header -->
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <!-- Logo -->
                <div class="header__logo">
                    <a href="<?php echo esc_url(home_url('/')); ?>" class="logo" aria-label="株式会社光和 ホームページ">
                        <img src="<?php echo esc_url(get_theme_file_uri('images/logo.png')); ?>" alt="株式会社光和ロゴ" class="logo__image">
                        <!-- TODO: images/logo_kowa.png を配置したら完了 -->
                        <img src="<?php echo esc_url(get_theme_file_uri('images/logo_kowa.png')); ?>" alt="光和" class="logo__kowa">
                    </a>
                </div>

                <!-- Desktop Navigation -->
                <nav id="nav" class="header__nav" role="navigation" aria-label="メインナビゲーション">
                    <ul class="nav__list">
                        <!-- <li class="nav__item">
                            <a href="<?php echo home_url('/') ?>" class="nav__link" aria-current="page">
                                <i class="fas fa-home nav__icon" aria-hidden="true"></i>
                                <span>トップ</span>
                            </a>
                        </li> -->
                        <li class="nav__item">
                            <a href="<?php echo esc_url(home_url('/#plans')); ?>" class="nav__link">
                                <i class="fas fa-list-alt nav__icon" aria-hidden="true"></i>
                                <span>葬儀プラン</span>
                            </a>
                        </li>
                        <li class="nav__item">
                            <a href="<?php echo esc_url(home_url('/#facilities')); ?>" class="nav__link">
                                <i class="fas fa-building nav__icon" aria-hidden="true"></i>
                                <span>式場・施設案内</span>
                            </a>
                        </li>
                        <li class="nav__item nav__item--dropdown">
                            <button class="nav__link nav__dropdown-toggle"
                                    aria-expanded="false"
                                    aria-haspopup="true"
                                    data-dropdown="funeral-info">
                                <i class="fas fa-info-circle nav__icon" aria-hidden="true"></i>
                                <span>葬儀について</span>
                                <i class="fas fa-chevron-down nav__arrow" aria-hidden="true"></i>
                            </button>
                            <ul class="dropdown" id="funeral-info-dropdown" role="menu" aria-labelledby="funeral-info">
                                <li class="dropdown__item" role="none">
                                    <a href="<?php echo esc_url(home_url('/soudan/')); ?>" class="dropdown__link" role="menuitem">
                                        <i class="fas fa-user-tie" aria-hidden="true"></i>
                                        <span>事前相談</span>
                                    </a>
                                </li>
                                <li class="dropdown__item" role="none">
                                    <a href="<?php echo esc_url(home_url('/#flow')); ?>" class="dropdown__link" role="menuitem">
                                        <i class="fas fa-route" aria-hidden="true"></i>
                                        <span>葬儀の流れ</span>
                                    </a>
                                </li>
                                <li class="dropdown__item" role="none">
                                    <a href="<?php echo esc_url(home_url('/#manner')); ?>" class="dropdown__link" role="menuitem">
                                        <i class="fas fa-hand-peace" aria-hidden="true"></i>
                                        <span>葬儀のマナー</span>
                                    </a>
                                </li>
                                <li class="dropdown__item" role="none">
                                    <a href="<?php echo esc_url(home_url('/#faq')); ?>" class="dropdown__link" role="menuitem">
                                        <i class="fas fa-question-circle" aria-hidden="true"></i>
                                        <span>よくある質問</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav__item">
                            <a href="<?php echo esc_url(home_url('/flower/')); ?>" class="nav__link">
                                <i class="fas fa-seedling nav__icon" aria-hidden="true"></i>
                                <span>供花・生花</span>
                            </a>
                        </li>
                        <li class="nav__item">
                            <a href="<?php echo esc_url(home_url('/company/')); ?>" class="nav__link">
                                <i class="fas fa-users nav__icon" aria-hidden="true"></i>
                                <span>会社案内</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
        </div>

    </header>

    <!-- Mobile Menu Overlay (headerの外に配置 - backdrop-filterによるposition:fixed問題回避) -->
    <div class="mobile-menu-overlay" id="mobile-menu-overlay"></div>

    <!-- Mobile Menu -->
    <nav class="mobile-menu" id="mobile-menu" role="navigation" aria-label="モバイルメニュー">
        <div class="mobile-menu__header">
            <span class="mobile-menu__title">メニュー</span>
            <button class="mobile-menu__close" aria-label="メニューを閉じる">
                <i class="fas fa-times" aria-hidden="true"></i>
            </button>
        </div>
        <ul class="mobile-menu__list">
            <!-- <li class="mobile-menu__item">
                <a href="<?php echo home_url('/') ?>" class="mobile-menu__link" aria-current="page">
                    <i class="fas fa-home" aria-hidden="true"></i>
                    <span>トップ</span>
                </a>
            </li> -->
            <li class="mobile-menu__item">
                <a href="<?php echo esc_url(home_url('/#plans')); ?>" class="mobile-menu__link">
                    <i class="fas fa-list-alt" aria-hidden="true"></i>
                    <span>葬儀プラン</span>
                </a>
            </li>
            <li class="mobile-menu__item">
                <a href="<?php echo esc_url(home_url('/#facilities')); ?>" class="mobile-menu__link">
                    <i class="fas fa-building" aria-hidden="true"></i>
                    <span>式場・施設案内</span>
                </a>
            </li>
            <li class="mobile-menu__item mobile-menu__item--expandable">
                <button class="mobile-menu__link mobile-menu__expand-toggle"
                        aria-expanded="false"
                        data-target="funeral-submenu">
                    <i class="fas fa-info-circle" aria-hidden="true"></i>
                    <span>葬儀について</span>
                    <i class="fas fa-chevron-down mobile-menu__arrow" aria-hidden="true"></i>
                </button>
                <ul class="mobile-submenu" id="funeral-submenu">
                    <li class="mobile-submenu__item">
                        <a href="<?php echo esc_url(home_url('/soudan/')); ?>" class="mobile-submenu__link">
                            <i class="fas fa-user-tie" aria-hidden="true"></i>
                            <span>事前相談</span>
                        </a>
                    </li>
                    <li class="mobile-submenu__item">
                        <a href="<?php echo esc_url(home_url('/#flow')); ?>" class="mobile-submenu__link">
                            <i class="fas fa-route" aria-hidden="true"></i>
                            <span>葬儀の流れ</span>
                        </a>
                    </li>
                    <li class="mobile-submenu__item">
                        <a href="<?php echo esc_url(home_url('/#manner')); ?>" class="mobile-submenu__link">
                            <i class="fas fa-hand-peace" aria-hidden="true"></i>
                            <span>葬儀のマナー</span>
                        </a>
                    </li>
                    <li class="mobile-submenu__item">
                        <a href="<?php echo esc_url(home_url('/#faq')); ?>" class="mobile-submenu__link">
                            <i class="fas fa-question-circle" aria-hidden="true"></i>
                            <span>よくある質問</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="mobile-menu__item">
                <a href="<?php echo esc_url(home_url('/flower/')); ?>" class="mobile-menu__link">
                    <i class="fas fa-seedling" aria-hidden="true"></i>
                    <span>供花・生花</span>
                </a>
            </li>
            <li class="mobile-menu__item">
                <a href="<?php echo esc_url(home_url('/company/')); ?>" class="mobile-menu__link">
                    <i class="fas fa-users" aria-hidden="true"></i>
                    <span>会社案内</span>
                </a>
            </li>
        </ul>

        <!-- Mobile Menu CTA -->
        <div class="mobile-menu__cta">
            <a href="tel:0120-077-508" class="btn btn--primary btn--lg">
                <i class="fas fa-phone" aria-hidden="true"></i>
                <span>今すぐ相談</span>
            </a>
            <!-- <a href="#contact" class="btn btn--secondary btn--lg">
                <i class="fas fa-file-alt" aria-hidden="true"></i>
                <span>資料請求</span>
            </a> -->
        </div>
    </nav>